name: Defense Evasion, T1562.001 - Usage of SystemSettingsAdminFlows.exe to tamper with Windows Defender
index_type: events
description: Detects the usage of SystemSettingsAdminFlows.exe to disable or tamper with Windows Defender. This behavior was observed being used by Inc ransomware threat group.
references:
    - https://www.huntress.com/blog/lolbin-to-inc-ransomware
    - https://attack.mitre.org/techniques/T1562/001/
tags: defense_evasion, t1562.001
search_query: os_type:windows AND (process_name:systemsettingsadminflows.exe OR original_filename:systemsettingsadminflows.exe) AND cmdline:defender AND ((cmdline:1 AND (cmdline:disableenhancednotifications OR cmdline:rtp)) OR (cmdline:0 AND (cmdline:spynetreporting OR cmdline:submitsamplesconsent)))
on_hit: alert, syslog
