name: Cobalt Strike - Usage of DLL search order hijacking to spawn SQL Server Client Config utility
index_type: events
description: Detects the usage of DLL search order hijacking used by CS to bypass UAC by spawning SQL server client config utility.
references: https://redcanary.com/threat-detection-report/threats/cobalt-strike/
tags: cobalt_strike, c2
search_query: parent_name:rundll32.exe AND process_name:cliconfg.exe
on_hit: alert, syslog